### ISSUE TITLE
企业微信cookie有效，但是无法刷新IP

### ISSUE THREAD

**Issue by tadgtd** [suraxiuxiu/WeworkAutoIpConfig#7]
检测周期为：
* 0/1 * * * ? *

Pending jobs:
    检测公网IP (trigger: date[2024-10-31 18:06:06 CST], pending)
    延续企业微信cookie有效时间 (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='*/5'], pending)
ERROR:   scheduler.py - 运行插件 WeWorkIPPW 服务失败：Wrong number of fields; got 7, expected 5 - Traceback (most recent call last):
  File "/app/app/scheduler.py", line 408, in update_plugin_job
    plugin_services = PluginManager().run_plugin_method(pid, "get_service") or []
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/core/plugin.py", line 542, in run_plugin_method
    return getattr(plugin, method)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/weworkippw/__init__.py", line 513, in get_service
    "trigger": CronTrigger.from_crontab(self._cron),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/apscheduler/triggers/cron/__init__.py", line 101, in from_crontab
    raise ValueError('Wrong number of fields; got {}, expected 5'.format(len(values)))
ValueError: Wrong number of fields; got 7, expected 5

INFO:     10.0.10.2:0 - "PUT /api/v1/plugin/WeWorkIPPW HTTP/1.1" 200 OK
INFO:     10.0.10.2:0 - "GET /api/v1/plugin/?state=installed HTTP/1.1" 200 OK
INFO:    plugin.py - 共获取到 195 个线上插件
INFO:     10.0.10.2:0 - "GET /api/v1/plugin/?state=market HTTP/1.1" 200 OK
INFO:    weworkippw - 开始检测公网IP
INFO:    weworkippw - IP获取成功: https://myip.ipip.net: 39.……
INFO:    weworkippw - 检测公网IP完毕

【INFO】2024-10-31 18:06:06,857 - weworkippw - 检测公网IP完毕
【INFO】2024-10-31 18:06:06,856 - weworkippw - IP获取成功: https://myip.ipip.net: 39.……
【INFO】2024-10-31 18:06:06,752 - weworkippw - 开始检测公网IP
【INFO】2024-10-31 18:06:03,750 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 18:06:03,749 - weworkippw - 立即检测公网IP                                            #手动刷新
【INFO】2024-10-31 18:05:22,370 - weworkippw - 检测公网IP完毕
【INFO】2024-10-31 18:05:22,369 - weworkippw - IP获取成功: https://myip.ipip.net: 39.……
【INFO】2024-10-31 18:05:22,266 - weworkippw - 开始检测公网IP
【INFO】2024-10-31 18:05:19,266 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 18:05:19,265 - weworkippw - 立即检测公网IP                                            #手动刷新
【INFO】2024-10-31 18:05:05,023 - weworkippw - cookie有效校验成功
【INFO】2024-10-31 18:05:00,001 - weworkippw - 开始刷新企业微信缓存
【INFO】2024-10-31 18:03:34,094 - weworkippw - 检测公网IP完毕
【INFO】2024-10-31 18:03:34,017 - weworkippw - 更改第1个应用的可信IP成功
【INFO】2024-10-31 18:03:30,882 - weworkippw - 正在更改第1个应用的可信IP
【INFO】2024-10-31 18:03:30,881 - weworkippw - 加载企微管理界面成功
【INFO】2024-10-31 18:03:26,988 - weworkippw - 开始请求企业微信管理更改可信IP
【INFO】2024-10-31 18:03:26,987 - weworkippw - 检测到IP变化
【INFO】2024-10-31 18:03:26,986 - weworkippw - IP获取成功: https://myip.ipip.net: 39……
【INFO】2024-10-31 18:03:26,876 - weworkippw - 开始检测公网IP
【INFO】2024-10-31 18:03:23,877 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 18:03:23,874 - weworkippw - 立即检测公网IP                                            #手动刷新
【INFO】2024-10-31 18:03:02,694 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 18:00:06,799 - weworkippw - cookie有效校验成功
【INFO】2024-10-31 18:00:00,001 - weworkippw - 开始刷新企业微信缓存
【INFO】2024-10-31 17:59:11,384 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 17:58:36,978 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 17:55:04,824 - weworkippw - cookie有效校验成功
【INFO】2024-10-31 17:55:00,001 - weworkippw - 开始刷新企业微信缓存
【INFO】2024-10-31 17:54:29,047 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 17:52:12,524 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 17:51:22,451 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 17:49:16,205 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 17:45:05,008 - weworkippw - cookie有效校验成功
【INFO】2024-10-31 17:45:00,001 - weworkippw - 开始刷新企业微信缓存
【INFO】2024-10-31 17:44:26,562 - weworkippw - 创建定时刷新企业微信缓存任务
【INFO】2024-10-31 17:40:05,831 - weworkippw - cookie有效校验成功
【INFO】2024-10-31 17:40:00,001 - weworkippw - 开始刷新企业微信缓存

**Comment by tadgtd** [comment]
周期改为0 * * * *可以10分钟刷新一次

**Comment by tadgtd** [comment]
0/10 * * * *
10分钟每次的正确表达式
